version: 2
jobs:
  build-and-commit:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.727-node-browsers

    environment:
      JVM_OPTS: -Xmx3200m
      TZ: "Europe/Stockholm"

    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:AKBnW00688qMrbkk/zHqrO7lkN5KK5PqiMvz8mcnKcM"
      - checkout
      - run: make install
      - run: make release-frontend
      - run: mv -f ./resources/public/js/main.*.js ./
      - run: mv -f ./resources/public/index.html ./index.html.bak
      - run: mv -f ./resources/public/favicon.ico ./favicon.ico.bak
      - run:
          name: Commit to GitHub
          command: |
            git config user.email "jherrlin@gmail.com"
            git config user.name "CircleCI Job"
            git fetch --all
            rm -f package-lock.json
            git checkout gh-pages
            rm -rf ./js
            mkdir -p js
            mv -f main.*.js ./js/
            mv -f index.html.bak index.html
            mv -f favicon.ico.bak favicon.ico
            git add js index.html favicon.ico
            git commit --allow-empty -am "Latest build"
            git push -f origin gh-pages

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-commit:
          filters:
            branches:
              only: main
