version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: cimg/clojure:1.11.1-browsers

    environment:
      JVM_OPTS: -Xmx3200m
      TZ: "Europe/Stockholm"

    steps:
      - checkout
      - run: make circle-ci-test

  build-and-commit:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.727-node-browsers

    environment:
      JVM_OPTS: -Xmx3200m
      TZ: "Europe/Stockholm"

    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:AKBnW00688qMrbkk/zHqrO7lkN5KK5PqiMvz8mcnKcM"
      - checkout
      - run: make install
      - run: make release-frontend
      - run: make move-files-for-github-pages
      - run:
          name: Commit to GitHub
          command: ./scripts/commit-to-github-pages.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build-and-commit:
          filters:
            branches:
              only: main
