(ns se.jherrlin.music-theory.definitions.tone-values
  (:require
   [clojure.set :as set]
   [clojure.string :as str]
   [malli.core :as m]
   [se.jherrlin.music-theory.intervals :as intervals]
   [se.jherrlin.music-theory.models.tone :as models.tone]
   [se.jherrlin.utils :as utils]))


(comment
  (->> (let [tones       [#{:c}
                          #{:db :c#}
                          #{:d}
                          #{:d# :eb}
                          #{:e}
                          #{:f}
                          #{:gb :f#}
                          #{:g}
                          #{:g# :ab}
                          #{:a}
                          #{:bb :a#}
                          #{:b}]
             nr-of-tones (count tones)]
         (loop [[current-tone & rest] (take (* nr-of-tones 15) (cycle tones))
                value-coounter        0
                octave-counter        0
                acc                   {}]
           (if (= octave-counter 12)
             acc
             (recur
              rest
              (inc value-coounter)
              (if (current-tone :b) (inc octave-counter) octave-counter)
              (reduce
               (fn [m tone]
                 (assoc m
                        [tone octave-counter] value-coounter
                        [current-tone octave-counter] value-coounter
                        {:tone tone :octave octave-counter} value-coounter
                        {:tone current-tone :octave octave-counter} value-coounter))
               acc
               current-tone)))))
       (merge
        (let [tones       [#{:c}
                          #{:db :c#}
                          #{:d}
                          #{:d# :eb}
                          #{:e}
                          #{:f}
                          #{:gb :f#}
                          #{:g}
                          #{:g# :ab}
                          #{:a}
                          #{:bb :a#}
                          #{:b}]]
         (loop [[current-tone & rest] tones
                value-coounter        0
                acc                   {}]
           (if (nil? current-tone)
             acc
             (recur
              rest
              (inc value-coounter)
              (reduce
               (fn [m tone]
                 (assoc m
                        tone value-coounter
                        current-tone value-coounter))
               acc
               current-tone)))))))
  )

(defn vec-remove
  "remove elem in coll"
  [idx coll]
  (into (subvec coll 0 idx) (subvec coll (inc idx))))

(def tone-values
  {[:db 11]                       133,
   [#{:d} 2]                      26,
   {:tone :f#, :octave 7}         90,
   {:tone #{:d}, :octave 9}       110,
   {:tone #{:gb :f#}, :octave 8}  102,
   {:tone :f, :octave 11}         137,
   {:tone #{:g# :ab}, :octave 3}  44,
   [#{:f} 6]                      77,
   {:tone #{:e}, :octave 4}       52,
   {:tone :f, :octave 5}          65,
   {:tone #{:d}, :octave 3}       38,
   {:tone #{:g}, :octave 7}       91,
   [:c 9]                         108,
   :d#                            3,
   {:tone #{:d# :eb}, :octave 6}  75,
   {:tone #{:f}, :octave 3}       41,
   [:e 4]                         52,
   {:tone #{:g}, :octave 11}      139,
   {:tone #{:d# :eb}, :octave 9}  111,
   [#{:d} 9]                      110,
   [:d# 8]                        99,
   {:tone :d, :octave 10}         122,
   [:d 8]                         98,
   [:a# 4]                        58,
   {:tone :eb, :octave 1}         15,
   [:g# 5]                        68,
   #{:c}                          0,
   [#{:g} 2]                      31,
   {:tone #{:bb :a#}, :octave 7}  94,
   {:tone :e, :octave 8}          100,
   {:tone :gb, :octave 6}         78,
   {:tone :c, :octave 0}          0,
   {:tone :c, :octave 9}          108,
   [#{:a} 0]                      9,
   [#{:f} 2]                      29,
   [#{:c} 9]                      108,
   {:tone :c, :octave 8}          96,
   [#{:b} 10]                     131,
   [:bb 9]                        118,
   [:a 2]                         33,
   [:eb 10]                       123,
   [#{:d} 3]                      38,
   [:d 9]                         110,
   {:tone #{:a}, :octave 6}       81,
   {:tone :eb, :octave 8}         99,
   [:d# 2]                        27,
   {:tone :c, :octave 7}          84,
   [#{:bb :a#} 9]                 118,
   [#{:f} 4]                      53,
   :g#                            8,
   [:ab 10]                       128,
   [#{:gb :f#} 10]                126,
   [:g 10]                        127,
   [#{:a} 11]                     141,
   [:d# 1]                        15,
   {:tone #{:a}, :octave 2}       33,
   [:bb 1]                        22,
   [:c# 0]                        1,
   [#{:g} 6]                      79,
   {:tone :b, :octave 2}          35,
   {:tone :ab, :octave 8}         104,
   {:tone :g#, :octave 3}         44,
   [#{:db :c#} 6]                 73,
   [:a 11]                        141,
   {:tone #{:gb :f#}, :octave 5}  66,
   [#{:db :c#} 10]                121,
   {:tone :c, :octave 3}          36,
   [:c# 10]                       121,
   {:tone #{:gb :f#}, :octave 1}  18,
   {:tone #{:bb :a#}, :octave 1}  22,
   {:tone :ab, :octave 1}         20,
   #{:d}                          2,
   {:tone :a#, :octave 7}         94,
   [:g# 4]                        56,
   {:tone :b, :octave 9}          119,
   [:a# 2]                        34,
   {:tone #{:g}, :octave 2}       31,
   [:g# 11]                       140,
   {:tone :c#, :octave 7}         85,
   [:b 6]                         83,
   {:tone #{:a}, :octave 8}       105,
   [:f 10]                        125,
   {:tone :c, :octave 5}          60,
   [#{:g} 9]                      115,
   {:tone :f#, :octave 4}         54,
   {:tone :gb, :octave 8}         102,
   {:tone :a#, :octave 6}         82,
   [:a 10]                        129,
   [:bb 5]                        70,
   {:tone :ab, :octave 3}         44,
   {:tone #{:gb :f#}, :octave 11} 138,
   {:tone :g, :octave 11}         139,
   [#{:b} 8]                      107,
   [:b 9]                         119,
   {:tone #{:a}, :octave 7}       93,
   {:tone #{:b}, :octave 8}       107,
   [:d# 9]                        111,
   {:tone #{:a}, :octave 4}       57,
   {:tone #{:e}, :octave 6}       76,
   [:f 0]                         5,
   [#{:d# :eb} 1]                 15,
   {:tone #{:db :c#}, :octave 0}  1,
   {:tone :f#, :octave 1}         18,
   {:tone :ab, :octave 10}        128,
   {:tone #{:c}, :octave 7}       84,
   [#{:gb :f#} 11]                138,
   [#{:g# :ab} 0]                 8,
   {:tone #{:g}, :octave 9}       115,
   [:f 11]                        137,
   [#{:db :c#} 11]                133,
   [:gb 2]                        30,
   {:tone #{:f}, :octave 4}       53,
   {:tone :g#, :octave 5}         68,
   [:g 9]                         115,
   {:tone :f#, :octave 9}         114,
   [:g# 9]                        116,
   {:tone :d, :octave 6}          74,
   [:e 3]                         40,
   [:g 11]                        139,
   {:tone :g#, :octave 8}         104,
   [#{:bb :a#} 4]                 58,
   [#{:e} 2]                      28,
   {:tone :f#, :octave 11}        138,
   {:tone :db, :octave 7}         85,
   {:tone #{:g# :ab}, :octave 2}  32,
   [#{:db :c#} 2]                 25,
   {:tone #{:a}, :octave 5}       69,
   [#{:f} 0]                      5,
   [#{:d} 4]                      50,
   {:tone :gb, :octave 2}         30,
   {:tone #{:g# :ab}, :octave 5}  68,
   [:c 8]                         96,
   [#{:gb :f#} 2]                 30,
   {:tone #{:g}, :octave 0}       7,
   [:d 6]                         74,
   [:bb 10]                       130,
   {:tone :d#, :octave 4}         51,
   [:g# 3]                        44,
   {:tone #{:bb :a#}, :octave 5}  70,
   [:db 2]                        25,
   [:db 5]                        61,
   {:tone :e, :octave 9}          112,
   [#{:d} 11]                     134,
   {:tone :g#, :octave 2}         32,
   [:e 9]                         112,
   [:f 5]                         65,
   [#{:g# :ab} 6]                 80,
   [:d# 7]                        87,
   {:tone #{:d}, :octave 8}       98,
   [:db 0]                        1,
   {:tone :bb, :octave 1}         22,
   [:d 2]                         26,
   :bb                            10,
   [:eb 3]                        39,
   [#{:d} 0]                      2,
   {:tone :a, :octave 7}          93,
   {:tone #{:c}, :octave 2}       24,
   {:tone :b, :octave 4}          59,
   {:tone #{:gb :f#}, :octave 10} 126,
   [#{:gb :f#} 0]                 6,
   {:tone :gb, :octave 4}         54,
   {:tone #{:c}, :octave 6}       72,
   [:c# 4]                        49,
   {:tone :f, :octave 4}          53,
   {:tone #{:g}, :octave 8}       103,
   [#{:g} 7]                      91,
   [:g 7]                         91,
   [#{:bb :a#} 8]                 106,
   {:tone #{:b}, :octave 9}       119,
   [#{:d} 8]                      98,
   [#{:e} 10]                     124,
   {:tone #{:bb :a#}, :octave 9}  118,
   [:ab 11]                       140,
   {:tone #{:g# :ab}, :octave 10} 128,
   {:tone #{:g}, :octave 4}       55,
   {:tone :db, :octave 3}         37,
   #{:g}                          7,
   [:g# 2]                        32,
   {:tone #{:e}, :octave 9}       112,
   [:f# 6]                        78,
   {:tone :eb, :octave 2}         27,
   [:g# 7]                        92,
   {:tone #{:f}, :octave 5}       65,
   :db                            1,
   {:tone #{:f}, :octave 0}       5,
   {:tone :d#, :octave 0}         3,
   [:g# 6]                        80,
   {:tone #{:d}, :octave 4}       50,
   [:a# 1]                        22,
   {:tone :g#, :octave 11}        140,
   [:f 3]                         41,
   {:tone :b, :octave 6}          83,
   [:a# 10]                       130,
   [:e 6]                         76,
   [#{:c} 8]                      96,
   [:bb 11]                       142,
   [:gb 11]                       138,
   {:tone #{:d# :eb}, :octave 10} 123,
   {:tone #{:b}, :octave 0}       11,
   {:tone :db, :octave 6}         73,
   {:tone :f#, :octave 6}         78,
   [:d 10]                        122,
   {:tone #{:g}, :octave 10}      127,
   [:a 4]                         57,
   {:tone #{:a}, :octave 1}       21,
   {:tone #{:e}, :octave 2}       28,
   {:tone #{:db :c#}, :octave 7}  85,
   [#{:g} 4]                      55,
   {:tone #{:f}, :octave 1}       17,
   [:db 4]                        49,
   #{:b}                          11,
   {:tone :gb, :octave 0}         6,
   :gb                            6,
   {:tone :ab, :octave 4}         56,
   [#{:c} 0]                      0,
   #{:d# :eb}                     3,
   [:f 2]                         29,
   [#{:f} 8]                      101,
   [:f 7]                         89,
   [#{:f} 3]                      41,
   {:tone :bb, :octave 10}        130,
   [:db 7]                        85,
   {:tone #{:db :c#}, :octave 6}  73,
   {:tone :b, :octave 11}         143,
   {:tone #{:g# :ab}, :octave 9}  116,
   [:g 1]                         19,
   [:eb 6]                        75,
   [:c 5]                         60,
   {:tone :a, :octave 8}          105,
   {:tone :e, :octave 6}          76,
   {:tone #{:b}, :octave 7}       95,
   [:a# 6]                        82,
   [:gb 3]                        42,
   {:tone :a#, :octave 5}         70,
   {:tone :g, :octave 9}          115,
   [:c# 6]                        73,
   {:tone #{:d}, :octave 2}       26,
   [:g 3]                         43,
   {:tone #{:b}, :octave 1}       23,
   {:tone #{:g# :ab}, :octave 1}  20,
   #{:e}                          4,
   [#{:db :c#} 4]                 49,
   [:a 7]                         93,
   [#{:a} 6]                      81,
   {:tone #{:c}, :octave 0}       0,
   [#{:g} 1]                      19,
   {:tone :g, :octave 1}          19,
   {:tone :bb, :octave 2}         34,
   {:tone :g#, :octave 4}         56,
   {:tone :d, :octave 4}          50,
   {:tone #{:d# :eb}, :octave 1}  15,
   [:c 1]                         12,
   [#{:f} 5]                      65,
   {:tone #{:c}, :octave 11}      132,
   {:tone :c#, :octave 3}         37,
   {:tone :f, :octave 7}          89,
   {:tone #{:db :c#}, :octave 3}  37,
   [:g 5]                         67,
   [:eb 4]                        51,
   [:c 2]                         24,
   {:tone :a#, :octave 1}         22,
   [:bb 4]                        58,
   {:tone :f, :octave 1}          17,
   {:tone :f, :octave 2}          29,
   [:e 8]                         100,
   [#{:f} 1]                      17,
   [:a 3]                         45,
   [#{:bb :a#} 10]                130,
   {:tone :d, :octave 11}         134,
   {:tone :f#, :octave 5}         66,
   {:tone #{:b}, :octave 3}       47,
   {:tone #{:gb :f#}, :octave 4}  54,
   [:g 4]                         55,
   [:a 0]                         9,
   {:tone :c#, :octave 6}         73,
   [:b 8]                         107,
   [:d# 3]                        39,
   [#{:a} 7]                      93,
   {:tone #{:c}, :octave 5}       60,
   {:tone #{:d# :eb}, :octave 5}  63,
   {:tone #{:bb :a#}, :octave 0}  10,
   {:tone #{:d# :eb}, :octave 7}  87,
   [:f# 2]                        30,
   {:tone #{:e}, :octave 3}       40,
   {:tone :d#, :octave 5}         63,
   [#{:a} 8]                      105,
   {:tone :g, :octave 0}          7,
   {:tone :db, :octave 0}         1,
   [:c# 3]                        37,
   {:tone #{:e}, :octave 10}      124,
   [#{:e} 5]                      64,
   [#{:g# :ab} 2]                 32,
   {:tone :d, :octave 0}          2,
   {:tone #{:f}, :octave 9}       113,
   [:f 1]                         17,
   {:tone #{:bb :a#}, :octave 10} 130,
   [#{:e} 1]                      16,
   [:d 4]                         50,
   {:tone :eb, :octave 5}         63,
   [:f# 4]                        54,
   [#{:gb :f#} 8]                 102,
   {:tone #{:d}, :octave 7}       86,
   {:tone :e, :octave 1}          16,
   {:tone #{:bb :a#}, :octave 2}  34,
   [:db 8]                        97,
   {:tone #{:d# :eb}, :octave 0}  3,
   [:g# 10]                       128,
   :a#                            10,
   [#{:e} 8]                      100,
   [:d# 6]                        75,
   {:tone :eb, :octave 3}         39,
   {:tone #{:b}, :octave 6}       83,
   [:bb 7]                        94,
   {:tone :g, :octave 6}          79,
   [#{:db :c#} 7]                 85,
   [#{:gb :f#} 9]                 114,
   {:tone :a, :octave 11}         141,
   {:tone #{:c}, :octave 1}       12,
   [:g 6]                         79,
   {:tone #{:g}, :octave 5}       67,
   [#{:c} 6]                      72,
   [#{:d# :eb} 8]                 99,
   {:tone :gb, :octave 9}         114,
   {:tone #{:gb :f#}, :octave 0}  6,
   [#{:d# :eb} 10]                123,
   {:tone :e, :octave 10}         124,
   [:eb 11]                       135,
   [:db 1]                        13,
   {:tone #{:b}, :octave 5}       71,
   {:tone #{:a}, :octave 9}       117,
   [:f# 11]                       138,
   {:tone :b, :octave 3}          47,
   {:tone #{:e}, :octave 5}       64,
   {:tone :a, :octave 5}          69,
   {:tone :b, :octave 7}          95,
   {:tone :eb, :octave 10}        123,
   {:tone #{:f}, :octave 11}      137,
   {:tone :ab, :octave 2}         32,
   :e                             4,
   [#{:a} 2]                      33,
   {:tone :eb, :octave 11}        135,
   [:c 7]                         84,
   [:g 8]                         103,
   [:g# 1]                        20,
   {:tone :g, :octave 2}          31,
   [:a# 11]                       142,
   {:tone :g#, :octave 6}         80,
   {:tone :a, :octave 4}          57,
   [#{:bb :a#} 3]                 46,
   [:c 0]                         0,
   {:tone :f#, :octave 10}        126,
   #{:gb :f#}                     6,
   [:d 7]                         86,
   [#{:a} 5]                      69,
   [:c 10]                        120,
   {:tone :g#, :octave 10}        128,
   [:a# 0]                        10,
   [#{:f} 10]                     125,
   {:tone :ab, :octave 7}         92,
   [:e 5]                         64,
   {:tone :db, :octave 10}        121,
   {:tone :a#, :octave 0}         10,
   {:tone #{:b}, :octave 4}       59,
   {:tone :gb, :octave 11}        138,
   [#{:c} 5]                      60,
   [:db 9]                        109,
   {:tone #{:e}, :octave 8}       100,
   {:tone #{:d# :eb}, :octave 11} 135,
   [#{:d# :eb} 6]                 75,
   [#{:g} 8]                      103,
   {:tone #{:a}, :octave 3}       45,
   [#{:gb :f#} 4]                 54,
   [:c# 5]                        61,
   {:tone :d#, :octave 9}         111,
   [:f# 10]                       126,
   {:tone #{:b}, :octave 10}      131,
   [:c 3]                         36,
   [:c# 8]                        97,
   {:tone #{:f}, :octave 6}       77,
   [:b 0]                         11,
   {:tone #{:bb :a#}, :octave 3}  46,
   [#{:g# :ab} 7]                 92,
   {:tone :d, :octave 5}          62,
   [:c# 9]                        109,
   {:tone :f#, :octave 0}         6,
   {:tone :db, :octave 5}         61,
   {:tone #{:d}, :octave 0}       2,
   [:a 8]                         105,
   [:c# 2]                        25,
   {:tone :c, :octave 2}          24,
   {:tone #{:db :c#}, :octave 5}  61,
   {:tone :c#, :octave 9}         109,
   {:tone #{:bb :a#}, :octave 4}  58,
   {:tone :e, :octave 3}          40,
   {:tone :bb, :octave 6}         82,
   [:bb 3]                        46,
   [#{:gb :f#} 7]                 90,
   {:tone :f#, :octave 8}         102,
   {:tone :bb, :octave 5}         70,
   {:tone :gb, :octave 1}         18,
   [#{:g} 5]                      67,
   :g                             7,
   [#{:g# :ab} 5]                 68,
   {:tone #{:db :c#}, :octave 2}  25,
   [#{:gb :f#} 3]                 42,
   [:b 2]                         35,
   :c                             0,
   {:tone :g, :octave 4}          55,
   [:gb 7]                        90,
   [:f# 0]                        6,
   {:tone :c#, :octave 2}         25,
   {:tone :f#, :octave 2}         30,
   {:tone :f, :octave 6}          77,
   {:tone #{:g# :ab}, :octave 8}  104,
   [:ab 0]                        8,
   {:tone :ab, :octave 5}         68,
   {:tone #{:d}, :octave 1}       14,
   [#{:gb :f#} 1]                 18,
   {:tone :a#, :octave 3}         46,
   [:f# 3]                        42,
   {:tone #{:e}, :octave 11}      136,
   [:ab 3]                        44,
   [:db 3]                        37,
   [:e 7]                         88,
   {:tone :b, :octave 0}          11,
   {:tone :eb, :octave 0}         3,
   {:tone #{:db :c#}, :octave 1}  13,
   {:tone :a, :octave 6}          81,
   {:tone :bb, :octave 11}        142,
   [:ab 7]                        92,
   [:d 0]                         2,
   [:gb 6]                        78,
   [:d# 4]                        51,
   {:tone #{:gb :f#}, :octave 6}  78,
   [#{:a} 1]                      21,
   {:tone :c, :octave 1}          12,
   [:e 2]                         28,
   {:tone #{:db :c#}, :octave 9}  109,
   {:tone #{:g}, :octave 1}       19,
   [#{:bb :a#} 1]                 22,
   :f#                            6,
   {:tone :db, :octave 2}         25,
   :c#                            1,
   [#{:d# :eb} 2]                 27,
   {:tone #{:b}, :octave 11}      143,
   [:ab 5]                        68,
   {:tone :gb, :octave 7}         90,
   [:g# 0]                        8,
   {:tone :a#, :octave 2}         34,
   [#{:g# :ab} 3]                 44,
   {:tone :d, :octave 2}          26,
   {:tone #{:d}, :octave 11}      134,
   {:tone :db, :octave 9}         109,
   [#{:d# :eb} 3]                 39,
   [:f 6]                         77,
   [:gb 4]                        54,
   [:a 1]                         21,
   [#{:g} 11]                     139,
   [#{:d} 7]                      86,
   {:tone :d#, :octave 3}         39,
   {:tone :g, :octave 3}          43,
   [:f# 1]                        18,
   [:a# 5]                        70,
   [:gb 10]                       126,
   [#{:d} 1]                      14,
   {:tone #{:gb :f#}, :octave 7}  90,
   [#{:c} 3]                      36,
   [#{:gb :f#} 5]                 66,
   {:tone :gb, :octave 10}        126,
   {:tone :c#, :octave 10}        121,
   [#{:g# :ab} 11]                140,
   {:tone :e, :octave 7}          88,
   [:gb 1]                        18,
   [:c# 1]                        13,
   [:f 9]                         113,
   {:tone #{:c}, :octave 4}       48,
   [:b 11]                        143,
   {:tone :d#, :octave 1}         15,
   {:tone :g#, :octave 7}         92,
   [:ab 6]                        80,
   {:tone :eb, :octave 6}         75,
   [:ab 1]                        20,
   [#{:d} 6]                      74,
   {:tone :ab, :octave 9}         116,
   [:d# 5]                        63,
   {:tone :ab, :octave 0}         8,
   {:tone #{:c}, :octave 9}       108,
   {:tone :db, :octave 8}         97,
   {:tone :e, :octave 0}          4,
   #{:f}                          5,
   [:b 7]                         95,
   [:ab 2]                        32,
   {:tone #{:f}, :octave 7}       89,
   {:tone :g#, :octave 9}         116,
   {:tone :a, :octave 1}          21,
   [:eb 1]                        15,
   [:e 11]                        136,
   {:tone #{:e}, :octave 0}       4,
   {:tone :f, :octave 10}         125,
   [#{:c} 1]                      12,
   [#{:b} 2]                      35,
   [#{:e} 6]                      76,
   {:tone #{:d}, :octave 6}       74,
   {:tone :d, :octave 8}          98,
   {:tone :e, :octave 11}         136,
   [#{:bb :a#} 11]                142,
   {:tone :d#, :octave 6}         75,
   {:tone :bb, :octave 4}         58,
   {:tone :c#, :octave 1}         13,
   [#{:e} 4]                      52,
   {:tone #{:c}, :octave 8}       96,
   [:gb 9]                        114,
   {:tone :a#, :octave 8}         106,
   [#{:e} 11]                     136,
   [:gb 5]                        66,
   {:tone #{:d# :eb}, :octave 3}  39,
   {:tone #{:g}, :octave 3}       43,
   [#{:b} 9]                      119,
   [:ab 4]                        56,
   {:tone :bb, :octave 0}         10,
   #{:g# :ab}                     8,
   {:tone #{:a}, :octave 11}      141,
   [#{:d# :eb} 7]                 87,
   :b                             11,
   [#{:e} 0]                      4,
   {:tone :e, :octave 5}          64,
   {:tone :g, :octave 10}         127,
   {:tone :d, :octave 9}          110,
   [#{:g# :ab} 9]                 116,
   [:eb 5]                        63,
   [:d# 0]                        3,
   {:tone :b, :octave 8}          107,
   {:tone :a#, :octave 11}        142,
   [:eb 2]                        27,
   {:tone :b, :octave 5}          71,
   {:tone #{:db :c#}, :octave 8}  97,
   {:tone #{:e}, :octave 1}       16,
   [:b 10]                        131,
   {:tone :gb, :octave 5}         66,
   [#{:g} 0]                      7,
   [:c# 7]                        85,
   [:ab 8]                        104,
   [:d# 11]                       135,
   [:f# 7]                        90,
   [:e 1]                         16,
   {:tone :f#, :octave 3}         42,
   {:tone :a#, :octave 10}        130,
   {:tone #{:g# :ab}, :octave 0}  8,
   [:b 5]                         71,
   :d                             2,
   :f                             5,
   [#{:c} 7]                      84,
   {:tone #{:c}, :octave 3}       36,
   [#{:g# :ab} 1]                 20,
   {:tone :c#, :octave 5}         61,
   [:b 4]                         59,
   [#{:b} 1]                      23,
   [:a 6]                         81,
   [#{:bb :a#} 0]                 10,
   [:bb 6]                        82,
   {:tone #{:bb :a#}, :octave 8}  106,
   [#{:c} 10]                     120,
   [#{:a} 3]                      45,
   [:e 10]                        124,
   [#{:f} 7]                      89,
   [:a# 3]                        46,
   {:tone #{:db :c#}, :octave 10} 121,
   {:tone #{:g# :ab}, :octave 6}  80,
   {:tone :d#, :octave 8}         99,
   [#{:db :c#} 1]                 13,
   [#{:b} 4]                      59,
   {:tone #{:gb :f#}, :octave 9}  114,
   {:tone #{:g# :ab}, :octave 7}  92,
   {:tone :a#, :octave 9}         118,
   [#{:db :c#} 3]                 37,
   [#{:d# :eb} 4]                 51,
   {:tone :eb, :octave 4}         51,
   [#{:a} 4]                      57,
   [#{:b} 0]                      11,
   [#{:b} 6]                      83,
   [#{:g# :ab} 10]                128,
   [:g# 8]                        104,
   {:tone :g#, :octave 0}         8,
   {:tone :c#, :octave 11}        133,
   [#{:d# :eb} 11]                135,
   [:gb 0]                        6,
   {:tone #{:d# :eb}, :octave 2}  27,
   [:c 4]                         48,
   [:f 8]                         101,
   {:tone #{:d}, :octave 5}       62,
   [:a 5]                         69,
   [:c 6]                         72,
   {:tone :c, :octave 10}         120,
   [:eb 9]                        111,
   [#{:b} 7]                      95,
   {:tone :d, :octave 7}          86,
   {:tone :c#, :octave 4}         49,
   {:tone :a, :octave 0}          9,
   {:tone #{:gb :f#}, :octave 2}  30,
   [:bb 8]                        106,
   [#{:e} 3]                      40,
   :ab                            8,
   {:tone :f, :octave 3}          41,
   [:e 0]                         4,
   {:tone :db, :octave 1}         13,
   {:tone :db, :octave 4}         49,
   [:eb 0]                        3,
   [#{:a} 9]                      117,
   {:tone #{:d}, :octave 10}      122,
   {:tone :gb, :octave 3}         42,
   [#{:f} 11]                     137,
   [:c# 11]                       133,
   {:tone :c, :octave 11}         132,
   {:tone :f, :octave 9}          113,
   #{:a}                          9,
   [:f# 5]                        66,
   {:tone #{:gb :f#}, :octave 3}  42,
   [#{:bb :a#} 5]                 70,
   {:tone :c#, :octave 8}         97,
   [#{:g} 3]                      43,
   {:tone #{:f}, :octave 8}       101,
   [:gb 8]                        102,
   {:tone #{:bb :a#}, :octave 11} 142,
   [:g 0]                         7,
   {:tone :d#, :octave 11}        135,
   {:tone :e, :octave 2}          28,
   {:tone :ab, :octave 6}         80,
   {:tone #{:g# :ab}, :octave 4}  56,
   {:tone #{:a}, :octave 10}      129,
   [:a 9]                         117,
   {:tone :c, :octave 4}          48,
   [:db 6]                        73,
   {:tone :a#, :octave 4}         58,
   :eb                            3,
   {:tone :bb, :octave 9}         118,
   {:tone :g, :octave 8}          103,
   {:tone :bb, :octave 8}         106,
   [#{:db :c#} 0]                 1,
   [#{:bb :a#} 7]                 94,
   {:tone #{:d# :eb}, :octave 8}  99,
   [:db 10]                       121,
   [:d 3]                         38,
   [#{:b} 11]                     143,
   {:tone :g, :octave 7}          91,
   {:tone :eb, :octave 7}         87,
   [#{:bb :a#} 6]                 82,
   {:tone :a, :octave 10}         129,
   [:a# 8]                        106,
   {:tone #{:db :c#}, :octave 4}  49,
   {:tone #{:b}, :octave 2}       35,
   [#{:d# :eb} 0]                 3,
   {:tone :e, :octave 4}          52,
   [#{:db :c#} 5]                 61,
   [#{:d} 10]                     122,
   [:f 4]                         53,
   {:tone :d#, :octave 10}        123,
   {:tone #{:f}, :octave 10}      125,
   [:g 2]                         31,
   [#{:c} 2]                      24,
   [#{:d# :eb} 5]                 63,
   [:b 3]                         47,
   #{:bb :a#}                     10,
   [#{:a} 10]                     129,
   [#{:f} 9]                      113,
   [#{:c} 4]                      48,
   [:b 1]                         23,
   [:d 5]                         62,
   {:tone :a, :octave 9}          117,
   [:eb 8]                        99,
   {:tone :b, :octave 10}         131,
   {:tone :db, :octave 11}        133,
   {:tone :g#, :octave 1}         20,
   [:f# 9]                        114,
   [#{:db :c#} 9]                 109,
   {:tone :f, :octave 0}          5,
   [:c 11]                        132,
   [:a# 9]                        118,
   {:tone :b, :octave 1}          23,
   {:tone :c#, :octave 0}         1,
   {:tone :a, :octave 2}          33,
   [#{:e} 7]                      88,
   {:tone #{:bb :a#}, :octave 6}  82,
   {:tone :d#, :octave 7}         87,
   {:tone #{:f}, :octave 2}       29,
   {:tone :f, :octave 8}          101,
   {:tone #{:g}, :octave 6}       79,
   #{:db :c#}                     1,
   [#{:g# :ab} 4]                 56,
   [:d 11]                        134,
   [#{:c} 11]                     132,
   [#{:b} 5]                      71,
   [#{:d} 5]                      62,
   [:d# 10]                       123,
   {:tone :bb, :octave 7}         94,
   [:d 1]                         14,
   [:a# 7]                        94,
   [:ab 9]                        116,
   :a                             9,
   {:tone #{:a}, :octave 0}       9,
   {:tone #{:g# :ab}, :octave 11} 140,
   [:f# 8]                        102,
   {:tone :c, :octave 6}          72,
   {:tone :bb, :octave 3}         46,
   {:tone :d, :octave 1}          14,
   {:tone :eb, :octave 9}         111,
   {:tone #{:c}, :octave 10}      120,
   {:tone #{:d# :eb}, :octave 4}  51,
   {:tone #{:e}, :octave 7}       88,
   [:eb 7]                        87,
   {:tone :ab, :octave 11}        140,
   {:tone :d, :octave 3}          38,
   [:bb 0]                        10,
   {:tone #{:db :c#}, :octave 11} 133,
   [#{:g} 10]                     127,
   [#{:g# :ab} 8]                 104,
   [:bb 2]                        34,
   [#{:db :c#} 8]                 97,
   {:tone :a, :octave 3}          45,
   [#{:gb :f#} 6]                 78,
   [#{:d# :eb} 9]                 111,
   {:tone :d#, :octave 2}         27,
   [#{:e} 9]                      112,
   [#{:bb :a#} 2]                 34,
   [#{:b} 3]                      47,
   {:tone :g, :octave 5}          67})

(comment
  (->> tone-values
       (sort-by second))
  )

(defn get-tone-value
  [x]
  (get tone-values x 0))

(get-tone-value [:b 2])    ;; => 35
(get-tone-value [:c 3])    ;; => 36
(get-tone-value [#{:c} 3]) ;; => 36

(defn compare-tones
  ([x]
   (get-tone-value x))
  ([x1 x2]
   (- (get-tone-value x1)
      (get-tone-value x2))))

(compare-tones [:b 2] [:b 2])
(compare-tones [#{:b} 2] [#{:c} 2])

(let [tones [[#{:a} 3] [#{:b} 3]]]
  (sort-by compare-tones tones))
;; => ([#{:a} 3] [#{:b} 3])


(defn drop-2 [tones]
  (let [[tone octave] (nth tones 1)
        tones' (vec-remove 1 tones)]
    (conj tones' [tone (inc octave)])))

(defn undo-drop-2 [tones]
  (let [[tone octave] (nth tones 3)]
    [(nth tones 0) [tone (dec octave)] (nth tones 1) (nth tones 2)]))



(let [stacked-tones-in-chord [[#{:d} 3]
                              [#{:gb :f#} 3]
                              [#{:a} 3]
                              [#{:db :c#} 4]]
      drop-2-voicing         [[#{:d} 3]
                              [#{:a} 3]
                              [#{:db :c#} 4]
                              [#{:gb :f#} 4]]]
  (= (drop-2 stacked-tones-in-chord)
     drop-2-voicing))

;; Dmaj7 stacked
(let [stacked-tones-in-chord [[#{:d} 3]
                              [#{:gb :f#} 3]
                              [#{:a} 3]
                              [#{:db :c#} 4]]]
  (->> stacked-tones-in-chord
       (drop-2)
       (undo-drop-2)
       (= stacked-tones-in-chord)))
